### ISSUE TITLE
Refresh flag not working

### ISSUE THREAD

**Issue by Bomb0ne** [foxy82/sunshine_utils#1]
Hi! I tried the --refreshrate as in description but it's not working, when used it even ignores the -p one for resolution (used alone no problem).
The command is something like:
"C:\temp\resolution_change.exe" -p 2k --refreshrate 60

is this the correct way it should be triggered?

**Comment by foxy82** [comment]
Hi - I've fixed this in version 0.2. However my monitor only supports a very limited set of resolutions (or so it seems) I've tested with --refreshrate 50 and --refreshrate 60.

My monitor supports 59.94 but it seems the Windows API wants an Int so I don't know how to set the monitor to that - so for now only ints are supported.
