### ISSUE TITLE
Virus Threat

### ISSUE THREAD

**Issue by kane9287** [foxy82/sunshine_utils#3]
This is showing as a virus taking defensive action to avoid Windows defender.

**Comment by foxy82** [comment]
Interesting. It doesn't on my Windows 11 install. 

You are welcome to check the code over in the repo and ensure you are happy with what it does. Also you can compile it yourself if you are worried about the exe that is uploaded being different from the source code. All details are in the README.md for creating the exe.

**Comment by kane9287** [comment]
I will clarify the title of this issue so it doesn't seem that I am declaring this a virus. I did in fact compile it myself and then scanned the .exe it also showed similar trojan threats. The source code doesn't seem to contain anything complex or malicious, perhaps its the compiling process itself or the way the code is written. I made this report so you are aware of the potential issue and can provide support or update the readme if you see more reports of similar behavior.

**Comment by foxy82** [comment]
In reality this would probably be best as a C# app but I'm not a C# coder.

There might be other alternatives to compile it. Alternatively with python installed on the sunshine host it might even be possible to run it directly.

**Comment by kane9287** [comment]
Basically using host cmd/terminal to execute Python and point it at the script? I hadn't considered that option as well. It's interesting that windows defender tagged it and so did my Kaspersky removal but when I ran it through Kaspersky scan tools it comes back clean. Is there a lot of malicious code written in Python? I'm still early in my knowledge of coding. I come from a hardware and IT background. 

If it was C# you could submit it as an official plugin for playnite as well. Could help integrate sunshine with their launcher. I don't know jack about C coding and I'm barely scratching the surface of JS and Python.

**Comment by foxy82** [comment]
I submitted it to VirusTotal and whilst a lot don't flag it some do:
https://www.virustotal.com/gui/file/6c282c9082fae5a29fb4ea260ae95cf5a800187f5e27edf2103c30610c9ac63f

 I guess with all things Python is easy to write - so it probably does attract a fair few viruses.
