### ISSUE TITLE
Preset - Failed to execute script 'resolution_change' due to unhandled exception!

### ISSUE THREAD

**Issue by mysteriousHerb** [foxy82/sunshine_utils#4]
D:\Gamestream\sunshine_utils\resolution_change.exe -p 1440p
Traceback (most recent call last):
  File "resolution_change.py", line 199, in <module>
TypeError: cannot unpack non-iterable NoneType object
[12148] Failed to execute script 'resolution_change' due to unhandled exception!

However, if speicfying width and height, it works.
D:\Gamestream\sunshine_utils\resolution_change.exe  --width 2560 --height 1440
Switching resolution to 2560x1440

**Comment by foxy82** [comment]
If you run with -h it will show you the help with the list of presets. 1440p isn't one of them.
