### ISSUE TITLE
Use New Sunshine Variables for WIDTH and HEIGHT

### ISSUE THREAD

**Issue by CorneliousJD** [foxy82/sunshine_utils#8]
The new version of sunshine shows the following new variables, including a height/width,

I was hoping we could use the following command, but it doesn't seem to work, any ideas?

**C:\Moonlight\resolution_changer\resolution_change.exe --width SUNSHINE_CLIENT_WIDTH --height SUNSHINE_CLIENT_HEIGHT -d "\\.\DISPLAY1" --detach-other-monitor**

I've tried it as above, and with quotes, and with %% before and after the variable names. 

About Environment Variables: All commands get these environment variables by default:
Var Name	
SUNSHINE_APP_ID	App ID
SUNSHINE_APP_NAME	App Name
SUNSHINE_CLIENT_WIDTH	The Width requested by the client
SUNSHINE_CLIENT_HEIGHT	The Height requested by the client
SUNSHINE_CLIENT_FPS	The FPS requested by the client
SUNSHINE_CLIENT_HDR	(true/false) if HDR is enabled by the client
SUNSHINE_CLIENT_GCMAP	(int) the requested gamepad mask, in a bitset/bitfield format
SUNSHINE_CLIENT_HOST_AUDIO	(true/false) if the client has requested host audio
SUNSHINE_CLIENT_ENABLE_SOPS	(true/false) if the client has requested the option to optimize the game for optimal streaming
SUNSHINE_CLIENT_AUDIO_CONFIGURATION	The Audio Configuration requested by the client (2.0/5.1/7.1)
Example - QRes for Resolution Automation:
cmd /C <qres path>\QRes.exe /X:%SUNSHINE_CLIENT_WIDTH% /Y:%SUNSHINE_CLIENT_HEIGHT%

**Comment by yodahekinsew** [comment]
I was able to get this working with the following command: 
`cmd /C "C:\Program Files\sunshine_utils\resolution_change.exe" --width %SUNSHINE_CLIENT_WIDTH% --height %SUNSHINE_CLIENT_HEIGHT% --refreshrate %SUNSHINE_CLIENT_FPS%`

**Comment by CorneliousJD** [comment]
Thanks, this does work for me -- I am using the --display with "\\.\DISPLAY7" w/ a dummy monitor and with that I found I cannot have cmd /C "program\path\resolution_change.exe" in quotes -- I had to have it in a path with no spaces so no quotes are around it, and then it all worked properly!
